0-linear:
	gcc -Wall -Wextra -Werror -pedantic 0-main.c 0-linear.c -o 0-linear
1-binary:
	gcc -Wall -Wextra -Werror -pedantic 1-main.c 1-binary.c -o 1-binary
100-jump:
	gcc -Wall -Wextra -Werror -pedantic 100-main.c 100-jump.c -lm -o 100-jump
102-interpolation:
	gcc -Wall -Wextra -Werror -pedantic 102-main.c 102-interpolation.c -o 102-interpolation
103-exponential:
	gcc -Wall -Wextra -Werror -pedantic 103-main.c 103-exponential.c -o 103-exponential
